staging: qca-wifi-host-cmn: fix build after disabling debug
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_event.c:363:54: error: expected expression
                        "Failed to add event in the list in %s", __func__),
                                                                          ^
1 error generated.

Change-Id: I0412209ffdbbeabb87a289b96e47f9785f18d23c
Signed-off-by: Akhil Narang <akhilnarang.1999@gmail.com>
Signed-off-by: sohamxda7 <sensoham135@gmail.com>
(cherry picked from commit 09e78952d358365c1e6a4c2476bdcf84fc06e9b2)